### ISSUE TITLE
possible to convert format 0 to 1 with SimpleMIDIFile ?

### ISSUE THREAD

**Issue by JoeriBultheel** [supercollider-quarks/wslib#16]
Hello,

Is it possible to convert a MIDI file's format by simply reading a file, setting its format property to 1, and then to write to a different location? This seems not to be working... 

Thnx

**Comment by woutersnoei** [comment]
correct, this is because type 0 and 1 files are structured differently. The SimpleMIDIFile will have to be inited using init0 or init1 to make it work correctly, and that assumes the midiEvents and metaEvents arrays to be empty. The difference is not very grave though, and with some study it should be possible to create a method or code to do it. Workaround could be to make a second empty SimpleMIDIFile with the desired format type, and then copy all midi events to it (which may also require some study to do correctly)..
