### ISSUE TITLE
Remove or fix Document extensions?

### ISSUE THREAD

**Issue by jamshark70** [supercollider-quarks/wslib#19]
https://github.com/supercollider-quarks/wslib/blob/master/wslib-classes/Lang/Workflow/extDocument-closeAllHelp.sc provides:

- `Document *closeAllHelp` -- outdated because we no longer open help files as documents.

- `Document *closeNoPath` -- whose purpose is not entirely clear to me, but which also appears outdated by reference to `listener`.

- `Document *closeObsolete` which calls both methods in succession.

https://github.com/supercollider-quarks/wslib/blob/master/wslib-classes/Lang/Workflow/extDocument-openStartup.sc provides:

- `Document *openStartup` -- possibly outdated because the IDE now has File > Open startup files (but possibly not outdated, because the platform might define multiple startup files and AFAIK the File command opens only one).

Because these extensions are not defined in a `scide_scqt` directory, sclang attempts to compile them when run from the command line as well, producing warnings that are disturbing to users.

Two options:

- Deprecate them (or just delete them) as outdated methods.

- Or move them into `Lang/Workflow/scide_scqt` (less disruptive, but that also means maintaining cruft).

I'm happy to do the PR, but I wanted to see what others think first.

**Comment by woutersnoei** [comment]
sorry for the lag, indeed these things can be either removed or updated to function in the current environment. I've held on to SC3.5 for quite some time for various reasons, which is why these things are still in there, but as the current wslib is on GitHub and the 3.5 compatible one on sf.net SVN we can actually update it without having to care about backwards compatibility. I'll try to look into these in the following weeks (hey, it's lockdown, so finally some time to work ;-) )

cheers & thanks!

**Comment by woutersnoei** [comment]
All removed now, they were indeed obsolete, thanks!
